# Generated by Django 4.2.16 on 2024-10-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to="tests.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="partners",
            field=models.ManyToManyField(blank=True, related_name="products", to="tests.partner"),
        ),
        migrations.CreateModel(
            name="SupplierMetadata",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("properties", models.CharField(max_length=255)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metadata", to="tests.supplier"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductMetadata",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("properties", models.CharField(max_length=255)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metadata", to="tests.product"
                    ),
                ),
            ],
        ),
    ]
